<?php

namespace AppBundle\Repository;

/**
 * ArmyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailable($id)
    {
        return $this->createQueryBuilder("a")
            ->where("a.userId = :id")
            ->andWhere('a.getThereOn is NULL')
            ->andWhere('a.getBackOn is NULL')
            ->setParameter("id", $id)
            ->getQuery()
            ->getResult();
    }
}
