<?php

namespace AppBundle\Repository;

/**
 * ArmyAssetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmyAssetsRepository extends \Doctrine\ORM\EntityRepository
{
}
