<?php

namespace AppBundle\Repository;

/**
 * AssetsOnRoadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetOnRoadRepository extends \Doctrine\ORM\EntityRepository
{
}
