<?php

namespace AppBundle\Repository;

/**
 * Asset_descrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Asset_descrRepository extends \Doctrine\ORM\EntityRepository
{
}
