<?php

namespace AppBundle\Repository;

/**
 * ColoniesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ColoniesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEnemies($id)
    {
        return $this->createQueryBuilder('c')
            ->where('c.user_id <> :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}