<?php

namespace AppBundle\Repository;

/**
 * ComunicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComunicationRepository extends \Doctrine\ORM\EntityRepository
{
}
